# Build pipeline

name: "Build self-hosted agent - '${{ parameters.ImageTag }}'"

parameters:
- name: ImageTag
  displayName: Docker image tag
  type: string
  default: 1.0.0

trigger:
- none

pool:
  name: Default

jobs:
- job:
  variables:
  - group: 'Pipeline variables'
  - name: DockerFile
    value: './Dockerfile'
  - name: WorkDir
    value: '.'
  - name: BuildArg
    value: 'APP_TARGET_DIR=target'
  - name: ImageName
    value: "azure-agent/self-hosted-agent"
  steps:

