# Build pipeline

name: "Build self-hosted agent - '${{ parameters.ImageTag }}'"

parameters:
- name: ImageTag
  displayName: Docker image tag
  type: string
  default: 1.0.0

trigger:
- none

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DevOps Bootcamp Docker Registry'
      repository: 'azure-agent/self-hosted-agent'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '${{ parameters.ImageTag }}'
      addPipelineData: false
      addBaseImageData: false
